insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Rudolph Cripps', 'RudolphCripps@gmail.com', '709-460-4232', 'Microsurgery Specialist', 'Plastic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Skip MacCracken', 'SkipMacCracken@gmail.com', '977-959-8245', 'Cardiologist', 'Cardiothoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Tuesday Strelitz', 'TuesdayStrelitz@gmail.com', '386-287-0444', 'Gastroenterologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Casey Perillo', 'CaseyPerillo@gmail.com', '634-236-8087', 'Hepatologist', 'Hepatobiliary Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Waldemar McDonagh', 'WaldemarMcDonagh@gmail.com', '478-929-6739', 'Nephrologist', 'Urology');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Mathew Rappoport', 'MathewRappoport@gmail.com', '519-713-8933', 'Pulmonologist', 'Thoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Camala Fyrth', 'CamalaFyrth@gmail.com', '266-544-1076', 'Endocrinologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Jone McJury', 'JoneMcJury@gmail.com', '137-498-2663', 'Ophthalmologist', 'Eye Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ('Carl Aimeric', 'CarlAimeric@gmail.com', '703-707-2112', 'Microsurgery Specialist', 'Plastic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Evaleen Cochrane', 'EvaleenCochrane@gmail.com', '392-444-3033', 'Cardiologist', 'Cardiothoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Siegfried Newe', 'SiegfriedNewe@gmail.com', '189-567-9924', 'Gastroenterologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Benji McKiddin', 'BenjiMcKiddin@gmail.com', '454-803-2642', 'Hepatologist', 'Hepatobiliary Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Lora Painswick', 'LoraPainswick@gmail.com', '229-796-2601', 'Nephrologist', 'Urology');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Susann Levens', 'SusannLevens@gmail.com', '548-733-6380', 'Pulmonologist', 'Thoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Clayborn Pamphilon', 'ClaybornPamphilon@gmail.com', '317-751-6059', 'Endocrinologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Eadmund Cinderey', 'EadmundCinderey@gmail.com', '559-231-5713', 'Ophthalmologist', 'Eye Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Ollie Gauvin', 'OllieGauvin@gmail.com', '989-342-9830', 'Microsurgery Specialist', 'Plastic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Burton de Quincey', 'BurtondeQuincey@gmail.com', '446-866-4857', 'Cardiologist', 'Cardiothoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Dorrie Simoncello', 'DorrieSimoncello@gmail.com', '863-109-6920', 'Gastroenterologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Sigfrid MacCahey', 'SigfridMacCahey@gmail.com', '137-676-1988', 'Hepatologist', 'Hepatobiliary Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Hamish De Launde', 'HamishDeLaunde@gmail.com', '657-841-3392', 'Nephrologist', 'Urology');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Harald Binley', 'HaraldBinley@gmail.com', '996-253-4037', 'Pulmonologist', 'Thoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Temp Samme', 'TempSamme@gmail.com', '428-629-2487', 'Endocrinologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Brnaba Akid', 'BrnabaAkid@gmail.com', '525-516-5181', 'Ophthalmologist', 'Eye Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Bonny Quinby', 'BonnyQuinby@gmail.com', '950-593-2216', 'Microsurgery Specialist', 'Plastic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Bendite Tomczak', 'BenditeTomczak@gmail.com', '905-332-3052', 'Cardiologist', 'Cardiothoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Brewster Omand', 'BrewsterOmand@gmail.com', '373-539-7397', 'Gastroenterologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Ralina Fern', 'Ralina Fern@gmail.com', '146-228-0533', 'Hepatologist', 'Hepatobiliary Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Renae Iuorio', 'RenaeIuorio@gmail.com', '792-433-1653', 'Nephrologist', 'Urology');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Bobbie Blick', 'BobbieBlick@gmail.com', '229-934-4119', 'Pulmonologist', 'Thoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Michal Anthonsen', 'MichalAnthonsen@gmail.com', '656-923-8458', 'Endocrinologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Harwell Strutt', 'HarwellStrutt@gmail.com', '323-487-8460', 'Ophthalmologist', 'Eye Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Nara Bassford', 'NaraBassford@gmail.com', '891-177-2267', 'Microsurgery Specialist', 'Plastic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Benson Eagle', 'BensonEagle@gmail.com', '788-998-2736', 'Cardiologist', 'Cardiothoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Keenan Filchagin', 'KeenanFilchagin@gmail.com', '670-319-7745', 'Gastroenterologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Sim Stang-Gjertsen', 'SimStang-Gjertsen@gmail.com', '149-524-6394', 'Hepatologist', 'Hepatobiliary Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Granny Littlecote', 'GrannyLittlecote@gmail.com', '444-997-5118', 'Nephrologist', 'Urology');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Jasmin Zappel', 'JasminZappel@gmail.com', '530-980-0246', 'Pulmonologist', 'Thoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Perla Revie', 'PerlaRevie@gmail.com', '517-352-4076', 'Endocrinologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Rollin Bodega', 'RollinBodega@gmail.com', '818-900-9148', 'Ophthalmologist', 'Eye Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Esmaria Norres', 'EsmariaNorres@gmail.com', '291-950-4540', 'Microsurgery Specialist', 'Plastic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Danny Baelde', 'DannyBaelde@gmail.com', '978-520-9847', 'Cardiologist', 'Cardiothoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Tomaso Plewman', 'TomasolPewman@gmail.com', '656-411-3808', 'Gastroenterologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Alia Gowan', 'AliaGowan@gmail.com', '273-771-4975', 'Hepatologist', 'Hepatobiliary Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Kendra Ughelli', 'KendraUghelli@gmail.com', '305-895-3072', 'Nephrologist', 'Urology');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Elka Salamon', 'ElkaSalamon@gmail.com', '185-994-8989', 'Pulmonologist', 'Thoracic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Melisandra Newbatt', 'MelisandraNewbatt@gmail.com', '365-109-6323', 'Endocrinologist', 'Transplant Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Ermengarde Micheli', 'ErmengardeMicheli@gmail.com', '922-959-4103', 'Ophthalmologist', 'Eye Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Walsh Purves', 'WalshPurves@gmail.com', '360-308-5005', 'Microsurgery Specialist', 'Plastic Surgery');
insert into Doctors (Doctor_Name, Doctor_Email, Contact, Specialist , Surgery_name) values ( 'Shamus McCloud', 'ShamusMcCloud@gmail.com', '179-714-7485', 'Cardiologist', 'Cardiothoracic Surgery');
