insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (13, '4/6/2026', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (94, '11/13/2020', 'Kidney');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (62, '4/28/2025', 'Pancreas');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (6, '6/8/2024', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (7, '8/20/2026', 'Pancreas');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (5, '12/5/2025', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (15, '8/16/2024', 'Kidney');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (46, '3/2/2027', 'Kidney');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (90, '5/20/2022', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (38, '4/30/2022', 'Kidney');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (17, '9/1/2026', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (19, '4/18/2021', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (53, '12/10/2025', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (81, '10/11/2024', 'Pancreas');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (21, '11/17/2023', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (100, '4/26/2022', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (82, '7/3/2025', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (60, '12/23/2020', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (58, '8/5/2025', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (28, '10/6/2024', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (57, '7/31/2022', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (31, '6/20/2024', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (32, '5/25/2020', 'Eyes');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (29, '7/24/2021', 'Eyes');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (34, '4/2/2021', 'Pancreas');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (35, '8/11/2024', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (52, '7/18/2023', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (36, '5/26/2022', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (37, '6/4/2026', 'Kidney');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (41, '6/16/2026', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (69, '5/31/2024', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (51, '11/30/2024', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (67, '2/11/2024', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (42, '1/31/2026', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (66, '6/26/2021', 'Eyes');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (45, '12/18/2025', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (77, '11/29/2024', 'Pancreas');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (50, '8/14/2020', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (48, '11/21/2025', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (54, '8/4/2024', 'Eyes');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (59, '5/17/2021', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (61, '10/29/2020', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (63, '7/31/2024', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (64, '4/14/2026', 'Lung');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (65, '9/11/2022', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (68, '10/18/2021', 'Kidney');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (70, '6/19/2020', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (74, '6/1/2025', 'Eyes');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (72, '3/14/2023', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (77, '1/15/2024', 'Vascularized allograft (VCA)');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (78, '12/23/2023', 'Lung');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (79, '11/9/2026', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (83, '11/29/2023', 'Liver');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (86, '12/10/2022', 'Lung');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (87, '12/25/2022', 'Eyes');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (88, '9/24/2025', 'Lung');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (93, '12/6/2026', 'Intestine');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (9, '5/11/2023', 'Kidney');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (8, '1/28/2023', 'Heart');
insert into Donor (Donor_ID, Donation_Date , Organ_Donated) values (39, '8/3/2025', 'Liver');
