insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('Transform Organ Donation Institute', '932-752-5930', 'RCUTjjZb');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('Transforming Lives Organ Donation Institute', '829-123-7379', 'VMWDYxNV');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('Legacy Organ Donation Center', '843-707-4242', 'YAZKtnEw');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('Inspiration Organ Donation Center', '340-572-9629', 'UOEGirJP');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('Bright Future Organ Donation Institute', '146-838-9518', 'MYOItUnn');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('Thrive Organ Donation Institute', '801-861-3053', 'AIOHwBAF');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('Brighter Future Organ Donation Institute', '854-368-5864', 'ZXISgGyJ');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('United Hearts Organ Donation Center', '597-768-2907', 'IFQKa7jF');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ('Inspiration Organ Donation Center', '497-634-9158', 'DDLOOD0s');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Legacy Organ Donation Center', '384-439-1087', 'BCSKIxoz');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Eternal Hope Organ Donation Center', '311-488-7120', 'PILWRV1f');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Transform Organ Donation Institute', '442-300-6993', 'VUSUkpIh');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Healing Hearts Organ Donation Center', '604-335-7014', 'ACBZSawu');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Renewal Organ Donation Institute', '985-302-9992', 'NIUVpetd');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Revive Organ Donation Institute', '773-850-1598', 'LOVPSs4J');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Bright Future Organ Donation Institute', '824-223-1680', 'FSPP8gyv');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Life Source Organ Donation Center', '345-975-9743', 'APFWRNUu');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Harmony in Life Organ Donation Center', '805-132-3668', 'TLZF79XL');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Renewal Organ Donation Institute', '967-769-9123', 'BKXUehEw');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Inspire Organ Donation Center', '270-794-4794', 'ABBNjHN9');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Thrive Organ Donation Institute', '202-746-5120', 'JJZCchSS');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Vitality Organ Donation Center', '751-799-3854', 'FQPGYEtQ');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Renewal Organ Donation Institute', '836-332-9292', 'DNJOOaZr');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Brighter Future Organ Donation Institute', '207-823-3693', 'WCZTInvk');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Bright Future Organ Donation Institute', '917-859-3866', 'QZFJpFcN');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Eternal Life Organ Donation Center', '887-801-5188', 'QERELn6P');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Empowerment Organ Donation Institute', '929-403-2848', 'GKTXdoX5');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Eternal Life Organ Donation Center', '449-770-2113', 'TKIWKI0t');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Inspiration Organ Donation Center', '281-397-4547', 'NPGNPkP3');
insert into Helping_Institutes (Institute_Name, Phone_Number, Registration_ID) values ( 'Brighter Future Organ Donation Institute', '952-328-5844', 'DKBQmvK3')